### ISSUE TITLE
[DOCS] Create Example Sections

### ISSUE THREAD

**Issue by bobluppes** [bobluppes/graaf#10]
# Create Example Sections
This is an open-ended issue and we welcome multiple PRs.

I would like to add a few example sections to the documentation. Each example should be self-contained and should demonstrate a potential usage of the Graaf library.

If you are interested, you can pick an example from the proposals below, or (even better) suggest your own example. The scope of a PR is restricted to a single example.

## Definition of Done
Each example should contain the following:

- [ ] A complete and self-contained example under `examples/EXAMPLE_NAME/main.cpp`.
  - To verify that the example compiles and runs.
  - This can be used to generate any graphics (via dot files) for the public documentation.
  - See the [dot serialization example](https://github.com/bobluppes/graaf/blob/main/examples/dot_serialization/main.cpp) for inspiration.
- [ ] An entry on our [public documentation](https://bobluppes.github.io/graaf/docs/examples/Intro).
  - A short description of the example, what is the use case and why is it typical.
  - A list of the Graaf algorithms and data structures which are demonstrated in the example. Here you can link to the respective [algorithms page](https://bobluppes.github.io/graaf/docs/algorithms/intro) in the documentation.
  - Code pointers (in the form of code blocks) to the important sections of the example. It is not necessary to cover the entirety of the added `main.cpp`, but the most important concepts should be captured.
  - Non-trivial parts in the code blocks should be explained in-text.
  - Graphics (i.e. in the form of visualized dot files) can be used. Any graphics should go under `docs/static/img/examples/.
  - Instructions on how to build the documentation locally can be found on the [wiki](https://github.com/bobluppes/graaf/wiki/development-setup#documentation).
  - An example entry can be found [here](https://bobluppes.github.io/graaf/docs/examples/example-basics/dot-serialization).

## Proposed Examples
- [x] Dot serialization
- [x] Shortest path (directed graph)
- [x] Shortest path (undirected graph) [@Hromz]
- [ ] Cycle detection [@Hromz] 
- [ ] Social network use case
- [ ] Minimal CNN implementation
- [ ] ...

**Comment by Hromz** [comment]
Hey @bobluppes, i would like to work on examples for documentation. Can i try?

**Comment by bobluppes** [comment]
Hi @Hromz, of course, looking forward to your contribution!

Please note that we have slightly changed the format we use for the examples. There is now a single source file with the example code under `examples/YOUR_EXAMPLE_NAME/`. Additionally, there is a docusaurus entry explaining it. I have updated this in the original issue and added links to the [wiki](https://github.com/bobluppes/graaf/wiki/development-setup#documentation) on how to build and host the documentation locally.

**Comment by Hromz** [comment]
Hey @bobluppes, I made PR #47. Can you take a look? Simple example that uses graph traversal and the shortest path. In the future, I will add better examples.

**Comment by Hromz** [comment]
@bobluppes can I work on cycle detection example?

**Comment by bobluppes** [comment]
> @bobluppes can I work on cycle detection example?

Hi @Hromz, of course! Looking forward to your contribution :)

**Comment by arnav1203** [comment]
Hey There. I would like to contribute in your repository so kindly grant me permission to do so.

**Comment by bobluppes** [comment]
> Hey There. I would like to contribute in your repository so kindly grant me permission to do so.

Hi @arnav1203, welcome to Graaf!
Of course! Would you be interested in working on the social network use case?

**Comment by Poornima2003** [comment]
can u plz assign me this issue , I would like to contribute to this issue .
