### ISSUE TITLE
[FEAT] Type overflow exception throw

### ISSUE THREAD

**Issue by Hromz** [bobluppes/graaf#100]
I think we should add a type overflow exception. The problem might occur while processing large inputs, especially in weighted shortest path algorithms.
I suggest using built-in functions or adding custom functions for integer and float point values.
As a temporary solution, we could use basic comparison, but in the future, do something more time and precision efficient.

What do you think about this?

Wikipedia
Integer values https://en.wikipedia.org/wiki/Integer_overflow  
Floating type values https://en.wikipedia.org/wiki/Floating-point_arithmetic

Also, if no one wants to do this, I would like to try. This one seems interesting.

**Comment by bobluppes** [comment]
Thanks for creating this issue, I think this would indeed be a good addition to the library!

Would your proposal be to introduce functions such as:

```c++
template <typename T>
T add_safe(T a, T b) {
  if (a > 0 && b > std::numeric_limits<T>::max() - a) // `a + b` would overflow => throw exception
  if (a < 0 && b < std::numeric_limits<T>::min() - a) // `a + b` would underflow => throw exception
  return a + b;
}
```

I will also think a bit about what the ideal way of doing this would be, let's use this issue to discuss.

**Comment by Hromz** [comment]
LGTM, also what do you think about to use built-in's sych as https://clang.llvm.org/docs/LanguageExtensions.html#builtin-functions ? For integer types.

**Comment by bobluppes** [comment]
> LGTM, also, what do you think about using built-ins such as https://clang.llvm.org/docs/LanguageExtensions.html#builtin-functions? For integer types. bool __builtin_add_overflow (type1 x, type2 y, type3 *sum); bool __builtin_sub_overflow (type1 x, type2 y, type3 *diff); bool __builtin_mul_overflow (type1 x, type2 y, type3 *prod); bool __builtin_uadd_overflow (unsigned x, unsigned y, unsigned *sum); bool __builtin_uaddl_overflow (unsigned long x, unsigned long y, unsigned long *sum); etc

Interesting, I have never used these before. My suggestion would be to encapsulate this in some central place of the codebase in some functions such as `add_safe`, `sub_safe`, and `mul_safe`. Then we can always easily change the implementation later if required.

Furthermore we would have to check what the compiler support is for these built-ins. It would be nice if the library can still be compiler agnostic.
