### ISSUE TITLE
Fix formatting in README

### ISSUE THREAD

**Issue by bobluppes** [bobluppes/graaf#106]
The project's `README.md` contains an overview of all currently implemented algorithms. The fifth item in this list ("Strongly Connected Component Algorithms") is not correctly formatted, resulting in preceding and succeeding `**`. This is probably due to an extra newline character in the markdown file.

The goal of this issue if to fix the formatting of the entry. Current:

>5. [**Strongly Connected Components Algorithms
>   **](https://bobluppes.github.io/graaf/docs/category/strongly-connected-components):
>    - Tarjan's Strongly Connected Components

Expected:

>5. [**Strongly Connected Components Algorithms**](https://bobluppes.github.io/graaf/docs/category/strongly-connected-components):
>    - Tarjan's Strongly Connected Components

While we are at it, let's also change the order of the algorithm categories such that they are in alphabetical order.

**Comment by dollarboysushil** [comment]
I want to work on this issue please assign it to me @bobluppes

**Comment by bobluppes** [comment]
> I want to work on this issue please assign it to me @bobluppes

Hi, welcome to the Graaf project @dollarboysushil! 
Of course, looking forward to your contribution :)

**Comment by exrol** [comment]
Hi, here is the PR https://github.com/bobluppes/graaf/pull/109

Bye !

**Comment by bobluppes** [comment]
> Hi, here is the PR #109
> 
> Bye !

Hi @exrol, unfortunately this issue was already assigned. But maybe you could take a look at some of the other issues. 
For instance, what do you think about #107?
