### ISSUE TITLE
Consistent naming of algorithm categories in documentation

### ISSUE THREAD

**Issue by bobluppes** [bobluppes/graaf#107]
The goal of this issue is to use a consistent naming scheme for the algorithm categories in the [documentation](https://bobluppes.github.io/graaf/docs/algorithms/intro).

Some algorithm categories have the `Algorithms` suffix (i.e. `Cycle Detection Algorithms`), while other categories do not (i.e. `Minimum Spanning Tree`). Lastly, not all algorithm descriptions are contained in a category (i.e. `Topological sort algorithm`).

I would propose to follow the algorithm category structure as present in the source code:

```
include
  + graaflib
     + algorithms
        + coloring
        + cycle detection
        + graph traversal
        + minimum spanning tree
        + shortest path
        + strongly connected components
        + topological sorting 
```

This issue is done when:
- The [documentation](https://bobluppes.github.io/graaf/docs/algorithms/intro) contains all categories listed above. Each category contains one or multiple `.md` files for the algorithms in that category.
- The naming of the algorithm categories follows the convention where each word is capitalized (`Cycle Detection` instead of `cycle detection`).
- The links in the `README.md`'s algorithm overview are adjusted to point to the new urls.

More details on how to generate the documentation locally can be found on [this wiki page](https://github.com/bobluppes/graaf/wiki/development-setup#documentation).

**Comment by isoletslicer** [comment]
Hello there, I'd like to contribute the documentation naming, would you mind to assign me?

I'm new into this C++ stuffs, is it okay?

**Comment by bobluppes** [comment]
> Hello there, I'd like to contribute the documentation naming, would you mind to assign me?
> 
> I'm new into this C++ stuffs, is it okay?

Hi, of course, welcome to Graaf! 

Also browsing these algorithm categories while working on it could be a great introduction to the code base!

**Comment by bobluppes** [comment]
Hi @isoletslicer, is this still on your radar?
