### ISSUE TITLE
Extract common test fixtures

### ISSUE THREAD

**Issue by bobluppes** [bobluppes/graaf#111]
We use the [GoogleTest](http://google.github.io/googletest/) framework for our unit tests. Since the Graaf library supports arbitrary vertex and edge types, we make use of `TYPED_TEST_SUITE`s to run our tests for different types of graph instances (i.e. `directed_graph<int, int>`, `directed_graph<long, std::string>`, ...).

Currently, most tests redefine the same fixtures over and over. For instance, consider `dijkstra_shortest_path_test.cpp` and `a_star_test.cpp`, which both define two sets of types (`weighted_graph_types` and `weighted_graph_signed_types`) in their anonymous namespace.

The goal of this issue is to extract these `types` and `fixture` definitions to a separate file `test/utils/fixtures.h`. This should make it easier to write tests in the future, as we can simply reuse the existing fixtures.

I would give all test files a once over to identify the fixtures we can extract, but in general I think all fixtures can be consolidated into either a fixture containing unsigned edge weights or a fixture containing signed edge weights.

More info on `gtest`'s TYPED_TEST_SUITE can be found [here](http://google.github.io/googletest/reference/testing.html#TYPED_TEST_SUITE).

**Comment by unbalancedvariance** [comment]
Hey can I work on this?
