### ISSUE TITLE
Installation guide is inconsistent

### ISSUE THREAD

**Issue by bobluppes** [bobluppes/graaf#125]
The installation guide in the readme and the one in the user documentation is different. We should unify these to avoid confusion. Furthermore we should check to see if the installation steps still work and update the guide where necessary.

**Comment by HarryHeres** [comment]
One quick note - if you follow the installation guide for a clangd LSP, the LSP does not consider the graaflib folder. 

![image](https://github.com/bobluppes/graaf/assets/74781187/4975513d-dd1d-429d-9b24-c936355c2b56)

That means if I do

```cpp
#include <graaflib/graph.h>
```

it will not find the file, but if I do 

```cpp
#include <graph.h>
```

it will.

My proposition is to update the docs to follow the PATH only to the "include" folder. 

PS: Also there's a typo in "graaflip"

**Comment by bobluppes** [comment]
> One quick note - if you follow the installation guide for a clangd LSP, the LSP does not consider the graaflib folder.
> 
> ![image](https://user-images.githubusercontent.com/74781187/273852536-4975513d-dd1d-429d-9b24-c936355c2b56.png)
> 
> That means if I do
> 
> ```c++
> #include <graaflib/graph.h>
> ```
> 
> it will not find the file, but if I do
> 
> ```c++
> #include <graph.h>
> ```
> 
> it will.
> 
> My proposition is to update the docs to follow the PATH only to the "include" folder.
> 
> PS: Also there's a typo in "graaflip"

Thanks for the details @HarryHeres! I will leave this issue up in case anyone is looking for an easy hacktoberfest contribution. Otherwise I will fix it myself next week

**Comment by aditya-borse** [comment]
I would like to work on unifying the installation guides. Please assign the issue to me so I can consolidate the documentation into the README. I've reviewed the current guides and believe I can complete this task. Let me know if you need any other info from me before assigning.

**Comment by bobluppes** [comment]
> I would like to work on unifying the installation guides. Please assign the issue to me so I can consolidate the documentation into the README. I've reviewed the current guides and believe I can complete this task. Let me know if you need any other info from me before assigning.

Hi @aditya-borse, would be happy to! Looking forward to your contribution :)

As a general remark, we currently have three places with installation instructions:
- In the README.md under the `Installation` section
- The [installation guide](https://bobluppes.github.io/graaf/docs/quickstart/installation) in the user facing documentation
- In a [readme](https://github.com/bobluppes/graaf/tree/main/include) in the include directory which will be bundled with each release.

I would not aim to consolidate everything in the main readme, instead what we should have is:
- The main readme which only contains the most basic installation option. Linking to the [installation guide](https://bobluppes.github.io/graaf/docs/quickstart/installation) for more option.
- The [installation guide](https://bobluppes.github.io/graaf/docs/quickstart/installation) which is very detailed
- A set of instructions bundled with each release, currently this lives in `include/README.md`. This should contain the basic installation instructions. For instance, take a look at either one of the `header-only` release artifacts on our [release](https://github.com/bobluppes/graaf/releases) page.

Any improvements or suggestions are more than welcome :)

**Comment by aditya-borse** [comment]
Hi @bobluppes, 
I've submitted a pull request ( #166 ) that addresses these issues. Kindly review it at your convenience and consider merging if it meets your approval.
Thanks for your time and consideration.
