### ISSUE TITLE
[DOCS] Broken image in readme

### ISSUE THREAD

**Issue by bobluppes** [bobluppes/graaf#155]
It seems like one of the images inside of the README has stopped working on Github:

![image](https://github.com/bobluppes/graaf/assets/18380160/eabd66fe-7211-4e58-b86e-9634d9ee4081)

After closer inspection, it seems like images within a quote block (`>`) are no longer being rendered correctly. Seeing as this worked before I am not sure if this change was intentional or a bug on Github's side. In any case, I would propose to move the image and the header out of the quote block for the time being.

Expected state:

![image](https://github.com/bobluppes/graaf/assets/18380160/2c8954ef-cf6d-4d49-b76e-8ad67b7f6cec)

**Comment by tvermaashutosh** [comment]
Please assign @bobluppes

**Comment by bobluppes** [comment]
> Please assign me this issue @bobluppes .

Hi, of course! Looking forward to your contribution :)
