### ISSUE TITLE
[FEAT] Adding Icons in the links section

### ISSUE THREAD

**Issue by ayushsgit** [bobluppes/graaf#158]
### Why is this important?
The UI will look better to the user

### Describe the solution you'd like
where ever there are links to a social like discord, github, etc. I will add icons there

### Are you willing to contribute?
I am willing to contribute

### Checklist
Please check the following before submitting the issue:

- [x] I have searched for similar feature requests in the issues.
- [x] This feature is not already implemented in the library.
- [x] I have provided a clear and concise description of the feature request.
- [x] I have explained why this feature is important and how it benefits the library and users.
- [x] I am willing to contribute to the development of this feature (if applicable).

Please note that feature requests are subject to review and may or may not be implemented in the library.

**Comment by bobluppes** [comment]
Hi @ayushsgit, thanks for creating the issue and welcome to Graaf :)

Do you mean to add these icons in the [user facing documentation](https://bobluppes.github.io/graaf/)? That would indeed be cool!

**Comment by ayushsgit** [comment]
yes

**Comment by bobluppes** [comment]
> yes

Awesome, assigning this to you then 🎉

**Comment by bobluppes** [comment]
Please take a look at [this wiki page](https://github.com/bobluppes/graaf/wiki/development-setup#documentation) for instructions on how to build and serve the documentation locally

**Comment by ayushsgit** [comment]
> Please take a look at [this wiki page](https://github.com/bobluppes/graaf/wiki/development-setup#documentation) for instructions on how to build and serve the documentation locally

Can you please tell where are the HTML and CSS files of the website , cause I am unable to find them in this code
