### ISSUE TITLE
[BUG] Unexpected move construction occru when adding vertex or edge

### ISSUE THREAD

**Issue by L-Sun** [bobluppes/graaf#170]
## Issue
When adding new vertex or edge lvalue to graph without `std::move`, the move construction of new vertex or edge is used. 

## Steps to reproduce
```cpp
graaf::directed_graph<std::string, std::string> graph;

std::string vertex_0 = "vertex_0";
std::string vertex_1 = "vertex_1";
std::string edge     = "edge";

auto vertex_id_0 = graph.add_vertex(vertex_0);
std::cout << (vertex_0.empty() ? "yes" : "no") << std::endl;  // yes

auto vertex_id_1 = graph.add_vertex(vertex_1);
std::cout << (vertex_1.empty() ? "yes" : "no") << std::endl;  // yes

graph.add_edge(vertex_id_0, vertex_id_1, edge);
std::cout << (edge.empty() ? "yes" : "no") << std::endl;  // yes
```

## Root Cause

In https://github.com/bobluppes/graaf/blob/58423fccf41e12f3b25303a3d70291335dda0de4/include/graaflib/graph.tpp#L140C1-L150C2
and
https://github.com/bobluppes/graaf/blob/58423fccf41e12f3b25303a3d70291335dda0de4/include/graaflib/graph.tpp#L170C1-L197C2

```cpp
template <typename VERTEX_T, typename EDGE_T, graph_type GRAPH_TYPE_V>
vertex_id_t graph<VERTEX_T, EDGE_T, GRAPH_TYPE_V>::add_vertex(auto&& vertex,
                                                              vertex_id_t id) {
  if (has_vertex(id)) {
    throw std::invalid_argument{"Vertex already exists at ID [" +
                                std::to_string(id) + "]"};
  }


  vertices_.emplace(id, std::forward<VERTEX_T>(vertex));
  //                                 ^^^^^^^^
  // vertices_.emplace(id, std::forward<decltype(vertex)>(vertex));  <- might be the correct implementation
  return id;
}
```
When using std::forward<VERTEX_T>, move construction will be involked, and the same applies to edge.

Here is a minimal code example that reproduces it without using graaf.
https://godbolt.org/z/1Eqdc6q5K

## Fix Ideas
As mentioned above, use `std::forward<decltype(vertex)>` instead of `std::forward<VERTEX_T>`, and the same applies to edge.

**Comment by joweich** [comment]
Hey @L-Sun, maybe I misunderstand your issue, but I'd argue that this is not a bug. Rather, invoking `move` when adding vertices/edges to the graph is the idiomatic way to go here.
If we used (more expensive) `copy` semantics instead, we would have two independent heap objects for the same thing - one in the client's code and one in the graph itself. This could lead to ambiguity and thus misuse, but is also worse in terms of performance.

To retrieve and use vertices/edges from the graph, use the getters:
```cpp
graaf::directed_graph<std::string, std::string> graph;

std::string vertex_0 = "vertex_0";
std::string vertex_1 = "vertex_1";
std::string edge     = "edge";

auto vertex_id_0 = graph.add_vertex(vertex_0);
auto vertex_id_1 = graph.add_vertex(vertex_1);
graph.add_edge(vertex_id_0, vertex_id_1, edge);

auto your_vertex = graph.get_vertex(vertex_id_0)
auto your_edge = graph.get_edge(vertex_id_0, vertex_id_1)
```
By moving the ownership of the objects into the graph, we make sure clients use the dedicated getters/setters while not making any compromises regarding performance and memory.
Let me know what you think! :slightly_smiling_face:

**Comment by L-Sun** [comment]
I'm relatively new to using graph libraries, so I wasn't familiar with the idiomatic way of working with them. I was actually guessing the usage based on how emplace_back works with std::vector. In std::vector, when adding new elements with emplace_back, unless explicitly using std::move, the copy constructor of the element is always invoked.

Thank you for clarifying the correct approach. I now have a better understanding of how to work with graphs. Appreciate your explanation!😊

**Comment by bobluppes** [comment]
Hi and sorry for parachuting in 😅 

I have given this some more thought and think you are right that this is a bug. While it is indeed more idiomatic to move expensive objects into the graph class by passing the ownership, it is still up to the user whether to do this or not.

As a user, I would indeed be very surprised if I choose not to pass ownership by pass an lvalue to `add_vertex` and all of a sudden my variable is in a moved-from state, leading to undefined behavior if I use that same variable again. i.e.

```c++
auto v = std::make_shared<my_class>();
const auto vertex_id = graph.add_vertex(v);

v->do_something();  // <- UB
```

I would only expect the variable to be moved when I explicitly pass an rvalue:

```c++
auto v = std::make_unique<my_class>();

const auto some_id = graph.add_vertex(std::move(v));
// OR
const auto some_other_id = graph.add_vertex(std::make_unique<my_class>());
```

So great find and thanks for reporting ☺️ 

I quickly tested your proposal and can verify that it works. I will re-open the ticket in case you or anyone else is interested in properly fixing this for the `add_vertex` and `add_edge` methods (including a test or two). Otherwise I can do so next week as well.
