### ISSUE TITLE
[FEAT] 支持 C++ 17 吗？

### ISSUE THREAD

**Issue by 18871434218** [bobluppes/graaf#189]
### Why is this important?
Explain why this feature is important for the library and how it can benefit the users.

### Are you willing to contribute?
Let us know if you are willing to contribute to the development of this feature.

### Checklist
Please check the following before submitting the issue:

- [ ] I have searched for similar feature requests in the issues.
- [ ] This feature is not already implemented in the library.
- [ ] I have provided a clear and concise description of the feature request.
- [ ] I have explained why this feature is important and how it benefits the library and users.
- [ ] I am willing to contribute to the development of this feature (if applicable).

Please note that feature requests are subject to review and may or may not be implemented in the library.

**Comment by bobluppes** [comment]
Hi @18871434218, could you explain your question in more detail?

The Graaf library natively supports C++17 as it was designed for use with C++20 (which is backwards compatible).

**Comment by bobluppes** [comment]
Closing this for now, feel free to re-open in case of any questions

**Comment by yolkarian** [comment]
I created a C++ 17 compatible fork [link] (https://github.com/yolkarian/graaf)
