### ISSUE TITLE
Add cycle detection algorithm

### ISSUE THREAD

**Issue by bobluppes** [bobluppes/graaf#19]
It would be nice to add an algorithm to detect whether a graph contains cycles. Two possible implementations here are Tarjan's algorithm and a depth-first search approach. Both implementations are valid candidates and could be added under this issue:

- [ ] Tarjan's algorithm (@bobluppes)
- [x] DFS cycle detection

The implementation should go under `src/graaflib/algorithm/cycle_detection.h`. Each implementation should be covered with unit tests and should have it's public interface documented with javadoc-style comments.

**Comment by Hromz** [comment]
Hello @bobluppes, can i do DFS cycle detection?

**Comment by bobluppes** [comment]
> Hello @bobluppes, can i do DFS cycle detection? :)

Hi @Hromz, of course! I have assigned you to it

**Comment by Hromz** [comment]
Created PR #42

**Comment by bobluppes** [comment]
FYI, closing this issue as I have created a new one for #53
