### ISSUE TITLE
How to perceive all the small cycles(https://www.pnas.org/doi/10.1073/pnas.0813040106)? Thanks!

### ISSUE THREAD

**Issue by zhangfq-chemistry** [bobluppes/graaf#196]

**Comment by bobluppes** [comment]
Hi @zhangfq-chemistry,  thank you for opening this issue and apologies for the late reply!

While we do have a cycle detection algorithm, we currently do not have any algorithms in place for extracting these cycles. Would you be interested in having a Smallest Set of Smallest Rings (SSSR) implementation? Additionally, it might be possible to implement this yourself using the `graph` interface. 

For now I will close this issue, but if this is still relevant for you then please feel free to provide more details and we can see if this is something we can include in `graaf`.
