### ISSUE TITLE
Add serialization

### ISSUE THREAD

**Issue by bobluppes** [bobluppes/graaf#21]
I would like to add support for writing graphs to files. At first, I would focus on the following formats:

- [x] dot (handled by @bobluppes)
- [ ] graphml
- [ ] json (handled by @misarb) 

Each of these could be implemented as a free function. Implementations should go under `src/graaflib/io`.

**Comment by JayPankajPatel** [comment]
Hey bob I'd like to help out

**Comment by bobluppes** [comment]
Hi @JayPankajPatel, thanks, that would be great!

Currently you can choose between adding serialization to `graphml` and to `json`, so feel free to pick whichever sounds more interesting to you.

**Comment by JayPankajPatel** [comment]
hey bob on second thought could you unassign this issue to me, I'm pretty busy with a personal project of mine.

**Comment by bobluppes** [comment]
> hey bob on second thought could you unassign this issue to me, I'm pretty busy with a personal project of mine.

Of course, no problem

**Comment by misarb** [comment]
hey @bobluppes can you assigne to me the `Json` format i would like to start working on it

**Comment by bobluppes** [comment]
> hey @bobluppes can you assigne to me the `Json` format i would like to start working on it

Hi @misarb, of course! I have assigned you to it

**Comment by bobluppes** [comment]
Hi @misarb, are you still working on this? I would close this issue for now as I want to focus on more algorithmic tickets. However, if you are up for it a PR is still welcome :) 

Let me know and we can reopen the issue.

**Comment by misarb** [comment]
Hey @bobluppes, I apologize for the late response. I've been really busy these past few days. I started implementing the serialization but encountered some problems during the build, as I mentioned on Discord. I'll try to complete it and send a PR.

**Comment by bobluppes** [comment]
Hi @misarb no worries. If you have time for it it will always be welcome, but no stress
