### ISSUE TITLE
[DOCS] Make minor improvements to development-setup

### ISSUE THREAD

**Issue by dksmiffs** [bobluppes/graaf#235]
- Use only one dash in the `clang-format` call preceding the `style` switch (two dashes don't work)
- Correct "VS Code" spelling
- Link to exaplanation of how to change VS Code settings

**Comment by dksmiffs** [comment]
I'm attaching my suggested patch.  I couldn't figure out how to push my branch to Github, since I didn't know how to fork the graaf.wiki repo in the normal Github way.
[0001-235-Improve-development-setup-page.patch](https://github.com/user-attachments/files/17135058/0001-235-Improve-development-setup-page.patch)

**Comment by joweich** [comment]
Hey @dksmiffs, thank you for your contribution! It looks like [clang-format v15](https://releases.llvm.org/15.0.0/tools/clang/docs/ClangFormatStyleOptions.html) uses the single-dash variant, while the latest [clang-format v20](https://clang.llvm.org/docs/ClangFormat.html) uses double-dash. I've validated that both single and double work for v20, so I tweaked the guide accordingly!
