### ISSUE TITLE
[ALGO] Kruskal's Minimum Spanning Tree

### ISSUE THREAD

**Issue by bobluppes** [bobluppes/graaf#52]
# Kruskal's Minimum Spanning Tree
Kruskal's algorithm find a minimum spanning forest of a (weighted) undirected graph. If the graph is connected this is a minimum spanning tree. See the [wikipedia](https://en.wikipedia.org/wiki/Kruskal%27s_algorithm) entry for more details.

## Syntax
The algorithm should have the following syntax:

```c++
/**
 * Computes the minimum spanning tree (MST) or minimum spanning forest of a graph 
 * using Kruskal's algorithm.
 *
 * @tparam V The vertex type of the graph.
 * @tparam E The edge type of the graph.
 * @param graph The input graph.
 * @return A vector of edges forming the MST or minimum spanning forest.
 */
template <typename V, typename E>
[[nodiscard]] std::vector<edge_id_t>
kruskal_minimum_spanning_tree(const graph<V, E, graph_type::UNDIRECTED>& graph);
```

This should live in the `graaf::algorithm` namespace under `include/graaflib/algorithm/minimum_spanning_tree.h`.

## Definition of Done
This issue is done when:

- [ ] The algorithm is implemented
- [ ] The new function has a javadoc-style comment explaining the interface
- [ ] Appropriate tests are added under `test/graaflib/algorithm/minimum_spanning_tree_test.cpp`
- [ ] A test coverage of at least 95% is reached
- [ ] A documentation entry is added under `docs/docs/algorithms` under the appropriate category
  - Just adding a short description and the algorithm syntax here is fine
  - See the [wiki](https://github.com/bobluppes/graaf/wiki/development-setup#documentation) on how to build the documentation locally
- [ ] The algorithm is added to the list of algorithms in `README.md`

**Comment by Hromz** [comment]
Hey @bobluppes! Assign to me please i wanna work on this after the docs.

**Comment by bobluppes** [comment]
Hi @Hromz, would be happy to, thanks!

**Comment by bobluppes** [comment]
> Hey @bobluppes! I have a question: in the example you provided, the function returns a vector of edge_t (weights), but not vertices with edge weights. Should I provide a realization with {vertex_a, vertex_b, weight} or use the example?

Hi @Hromz, good question! I have thought a bit about it and I would say a minimum spanning tree of a graph can be uniquely defined by a collection of edges (`edge_id_t`). Therefore I agree with you that returning a collection of `edge_t` does not make a lot of sense, sorry for the confusion 😅  

I think a `std::vector<edge_id_t`> should do nicely for our case.

**Comment by Hromz** [comment]
Hey @bobluppes i made PR #73

**Comment by bobluppes** [comment]
> Hey @bobluppes i made PR #73

Very nice, thanks for working on this 🎉 I will take a closer look this weekend.
