### ISSUE TITLE
[ALGO] Bellman-Ford Shortest Path

### ISSUE THREAD

**Issue by bobluppes** [bobluppes/graaf#55]
# Bellman-Ford Shortest Path
The Bellman-Ford algorithm computes the shortest path between a source vertex and all other vertices in the graph. Compared to Dijkstra, it can handle negative edge weights. See the [wikipedia](https://en.wikipedia.org/wiki/Bellman%E2%80%93Ford_algorithm) entry for more details.

## Syntax
The algorithm should have the following syntax:

```c++
template <typename V, typename E, graph_type T>
[[nodiscard]] return_type your_algorithm_name(const graph<V, E, T>& graph);

/**
 * Find the shortest paths from a source vertex to all other vertices using
 * the Bellman-Ford algorithm.
 *
 * @tparam V The vertex type of the graph.
 * @tparam E The edge type of the graph.
 * @tparam T The graph specialization (directed or undirected).
 * @tparam WEIGHT_T The type of weight associated with the edges.
 * @param graph The graph in which to find the shortest paths.
 * @param start_vertex The source vertex for the shortest paths.
 * @return A map of target vertex IDs to shortest path structures. Each
 *         value contains a graph_path object representing the
 *         shortest path from the source vertex to the respective vertex.
 *         If a vertex is unreachable from the source, its entry will be
 *         absent from the map.
 */
template <typename V, typename E, graph_spec T, typename WEIGHT_T = decltype(get_weight(std::declval<E>()))>
std::unordered_map<vertex_id_t, graph_path<WEIGHT_T>>
bellman_ford_shortest_paths(const graph<V, E, T>& graph, vertex_id_t start_vertex);

```

This should live in the `graaf::algorithm` namespace under `include/graaflib/algorithm/shortest_path.h`.

## Definition of Done
This issue is done when:

- [ ] The algorithm is implemented
- [ ] The new function has a javadoc-style comment explaining the interface
- [ ] Appropriate tests are added under `test/graaflib/algorithm/shortest_path_test.cpp`
- [ ] A test coverage of at least 95% is reached
- [ ] A documentation entry is added under `docs/docs/algorithms` under the appropriate category
  - Just adding a short description and the algorithm syntax here is fine
  - See the [wiki](https://github.com/bobluppes/graaf/wiki/development-setup#documentation) on how to build the documentation locally
- [ ] The algorithm is added to the list of algorithms in `README.md`

**Comment by ndcroos** [comment]
Hi, I'd like to work on this issue.

**Comment by bobluppes** [comment]
Awesome, I will assign the issue to you then! 

Feel free to take a look at the [wiki](https://github.com/bobluppes/graaf/wiki/overview) or join our discord in case of any questions.

**Comment by ndcroos** [comment]
Should the Bellman-Ford implementation also report negative-weight cycles? In that case, there is no shortest path. The Bellman-Ford algorithm can detect it.
Otherwise, I should mention it as a limitation in the docs.
I've implemented it now without that capability. Maybe it can be done later.

**Comment by bobluppes** [comment]
> Should the Bellman-Ford implementation also report negative-weight cycles? Wikipedia states that in the case of a negative-weight cycle that is reachable from the source, there is no shortest path.
> 
> The Bellman-Ford algorithm given on Wikipedia can detect a negative-weight cycle. If this check isn't implemented, I should mention it as a limitation in the docs.
> 
> I've implemented it now without that capability. Maybe it can be done later.

Good point! I think it would indeed make sense to detect this. Then we can omit that path from the result map. 

I would be fine with doing this in a follow-up. If you want you can create an issue for it :)
