### ISSUE TITLE
[DOCS] Document Dijkstra Shortest Path

### ISSUE THREAD

**Issue by bobluppes** [bobluppes/graaf#59]
# Documentation Dijkstra Shortest Path
The goal of this issue if the improve the documentation of an existing algorithm. This documentation should go into the algorithms section of our [docusaurus docs](https://bobluppes.github.io/graaf/docs/algorithms/intro).

More detail on how to build the documentation locally can be found on the [wiki](https://github.com/bobluppes/graaf/wiki/development-setup#documentation).

An existing documentation page exists, which should be extended. The page can be found under `docs/docs/algorithms/shortest-path/dijkstra.md`.

The corresponding algorithm is called `dijkstra_shortest_path` and can be found under `include/graaflib/algorithm/shortest_path.h`.

## Documentation Contents
The documentation entry should adhere to the following template:

```markdown
# [ALGORITHM_NAME]
- A short description of the algorithm, what does it do and in which use cases is it used.
- What are the limitations of the algorithm, does it work on both directed and undirected graphs? Does it consider edge weights, and if yes, does it support negative weights?
- Link to the wikipedia entry on the algorithm.

## Syntax
- A code block with the syntax of the algorithm. This should now include any javadoc comments.
- An explanation of the parameters (including template parameters) and the return type.

## (Optional) See also
- If there are similar algorithms, or we have a slightly different version of the same algorithm, you can link it here.
- If we have an example (found on the example page of the docs) which uses this algorithm, you can link it here.
```

**Comment by MichaeINeumann** [comment]
Hi, I would like to help but I have seen there is already a "docs: add documentation for dijkstra (#66)" added. Does this make this task obsolete, or is it to further improve dijkstra.md? I tried to install yarl, unfortunately without success. Is this mandatory or is it just to edit/enhance the markdown file.

**Comment by bobluppes** [comment]
Hi @MichaeINeumann, thanks for your interest! You are correct, in the other PR we added a documentation entry for both versions of the Dijkstra algorithm. I did however forget to close this ticket 😬 

If you are interested in picking up a documentation ticket, maybe one of the following could be of interest:
- #60 
- #58 
- #57 
- #56 

I would highly recommend installing `yarn` when working on the documentation, as it allows you to serve the documentation locally. This makes it very easy to observe the effect of your changes. If you have `npm` installed on your system you can install `yarn` using:

```bash
npm install --global yarn
```

On another note, I see that all algorithm tickets are assigned. I plan on adding more this afternoon in case you are interested.
