### ISSUE TITLE
Dockerized build

### ISSUE THREAD

**Issue by bobluppes** [bobluppes/graaf#61]
The goal of this issue is to dockerize the build process. This would be helpful since it enables developers to work on the project without installing all the build tools on their machine.

**Comment by MichaeINeumann** [comment]
I may have found a solution. 
Of course, for this ticket, a Dockerfile would also have to be created. 

I am still learning how this works exactly. 

But if no one else can be found, **I would like to try my hand at this task.**

Here is explaned how do Compile your app inside the Docker container:
https://hub.docker.com/_/gcc

Manuell Steps:
`
docker pull gcc
docker container create -it gcc  
`
id: 6c795b4b94d4bbc0b624114224376d4f0a825b14ce791e7b104febb9c91a5e99
`docker container start -i 6c795b4b94d4bbc0b624114224376d4f0a825b14ce791e7b104febb9c91a5e99     `

Container was started.

`root@6c795b4b94d4:/# g++ --version`
g++ (GCC) 13.2.0
`root@6c795b4b94d4:/# cd home`


 1) Clone the repository - clone your own fork if you want to contribute
git clone git@github.com:bobluppes/graaf.git
mkdir -p graaf/build && cd graaf/build

`root@6c795b4b94d4:/home/graaf/build# apt-get upgrade `
`root@6c795b4b94d4:/home/graaf/build# apt-get install cmake`


 2) Build the project
cmake ..
cmake --build .

 Run the tests to ensure everything is working correctly
ctest

-- Performing Test HAVE_PTHREAD_AFFINITY -- success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/graaf/build
[ 96%] Linking CXX executable Graaf_perf
[ 96%] Built target Graaf_perf
[ 98%] Building CXX object _deps/google_benchmark-build/src/CMakeFiles/benchmark_main.dir/benchmark_main.cc.o
[100%] Linking CXX static library libbenchmark_main.a
[100%] Built target benchmark_main
root@6c795b4b94d4:/home/graaf/build# ctest
265/265 Test #265: UnweightedGraphTest.AddUnweightedEdge<std::pair<graaf::graph<int, graaf::my_unweighted_edge<long double>, (graaf::graph_type)1>, graaf::my_unweighted_edge<long double> >> ................................................   Passed    0.00 sec

100% tests passed, 0 tests failed out of 265

Total Test time (real) =   1.34 sec

**Comment by bobluppes** [comment]
Hi @MichaeINeumann, do I understand you have the build working now? Congrats 🥳 

I see @misarb also has a PR(#74) open which adds a dockerfile. If you are up for trying it out their setup/providing feedback, maybe we can harmonize on the solution.

**Comment by MichaeINeumann** [comment]
Thank you very much for the explanation. I just wanted to understand. It seems my reasoning was correct. I'm fine with using header-only libraries and understand the need because of the generic approach. The idea of precompiled diagram types is interesting, but I am happy with the current setup.
