### ISSUE TITLE
Negative weight cycle detection in Bellman-Ford

### ISSUE THREAD

**Issue by bobluppes** [bobluppes/graaf#76]
Bellman-Ford does not work in the presence of negative weight cycles. We should detect this (by doing an additional pass over the edges) and report an error if these cycles occur.

**Comment by unbalancedvariance** [comment]
hey can i work on this issue?

**Comment by bobluppes** [comment]
Hi, welcome to Graaf :)
Of course! Looking forward to your contribution

**Comment by unbalancedvariance** [comment]
#97 Hey,can you check my work on this?
