### ISSUE TITLE
[REQUEST] Collaboration with CXXGraph

### ISSUE THREAD

**Issue by ZigRazor** [bobluppes/graaf#85]
Hi,

I'm the owner, coordinator and developer of a similar project [CXXGraph](https://github.com/ZigRazor/CXXGraph).
The project has the same goals, why not collaborate?
I think CXXGraph library is a step foward with also a community of users.
What do you think?

**Comment by bobluppes** [comment]
> What do you think?

Hi @ZigRazor, thanks for reaching out! I think your project looks interesting and I do indeed see potential for future collaboration. I would propose to discuss in some more detail on discord. Please feel free to join the [Graaf discord](https://discord.gg/cGczwRHJ9K) or to send me a message directly (`bluppes`).

**Comment by bobluppes** [comment]
Closing this issue for now, but feel free to reach out on our discord to discuss further!
