### ISSUE TITLE
[ALGO] Floyd-Warshall Shortest Paths

### ISSUE THREAD

**Issue by bobluppes** [bobluppes/graaf#89]
# Floyd-Warshall Shortest Paths
The Floyd-Warshall algorithm calculates the shortest distances between all pairs of vertices in a weighted graph. It is efficient and also works for graphs with negative edge weights, as long as there are no negative weight cycles. The algorithm is to be implemented as a free function in the Graaf library.

See the [wikipedia entry](https://en.wikipedia.org/wiki/Floyd%E2%80%93Warshall_algorithm) for more details.

## Syntax
The algorithm should have the following syntax:

```c++
/**
 * @brief Floyd-Warshall Algorithm
 *
 * This function computes the shortest paths between all pairs of vertices in a
 * given weighted graph. It works for graphs with negative weight edges as well,
 * but not for graphs with negative weight cycles. The function returns an
 * adjacency matrix representing the shortest distances.
 *
 * @tparam V The type of a graph vertex
 * @tparam E The type of a graph edge
 * @tparam T the graph type (DIRECTED or UNDIRECTED)
 * @tparam WEIGHT_T The weight type of an edge in the graph
 * @param graph The graph object
 * @return A 2D vector where element at [i][j] is the shortest distance from vertex i to vertex j.
 */
template <typename V, typename E, graph_type T, typename WEIGHT_T = decltype(get_weight(std::declval<E>()))>
std::vector<std::vector<WEIGHT_T>> floyd_warshall_shortest_paths(const graph<V, E, T>& graph);
```

This should live in the `graaf::algorithm` namespace under `include/graaflib/algorithm/shortest_path/floyd_warshall.h`. There already exists a source file `include/graaflib/algorithm/shortest_path.h`, but I would like to split this up in the future. Therefore please create a directory `shortest_path` in which we can place `floyd_warshall.h`.

## Definition of Done
This issue is done when:

- [ ] The algorithm is implemented
- [ ] The new function has a javadoc-style comment explaining the interface
- [ ] Appropriate tests are added under `test/graaflib/algorithm/shortest_path/floyd_warshall_test.cpp`
- [ ] A test coverage of at least 95% is reached
- [ ] A documentation entry is added under `docs/docs/algorithms` under the appropriate category
  - Just adding a short description and the algorithm syntax here is fine
  - See the [wiki](https://github.com/bobluppes/graaf/wiki/development-setup#documentation) on how to build the documentation locally
- [ ] The algorithm is added to the list of algorithms in `README.md`

**Comment by Hromz** [comment]
Hey @bobluppes, can I work on this after TS?

**Comment by bobluppes** [comment]
> Hey @bobluppes, can I work on this after TS?

Would be happy to :)

**Comment by bobluppes** [comment]
> I am also interested in this @bobluppes

Hi @R055A, welcome to Graaf 🎉 

Unfortunately @Hromz was first on the issue. Would you be interested in either:
- The [Page Rank algorithm](https://github.com/bobluppes/graaf/issues/90)
- The [Bron-Kerbosch algorithm](https://github.com/bobluppes/graaf/issues/95)

If you would prefer to work on a shortest path algorithm (or anything else of your choosing for that matter) feel free to let me know and I will spawn a ticket accordingly.

Looking forward to your contributions :)

**Comment by Hromz** [comment]
Check #98
